### ISSUE TITLE
Firefox 17 breaks gritter

### ISSUE THREAD

**Issue by nurettin** [jboesch/Gritter#34]
Gritter doesn't show on the first call, then works OK after second call. 
Demo page shows the same problem.

**Comment by ghost** [comment]
I had the same problem. 

I first thought it was a problem with the fadeIn function of jquery, but after testing the plugin on several machines, the problem only occured on one system.

I followed the troubleshotting guide of Firefox (http://support.mozilla.org/en-US/kb/troubleshoot-and-diagnose-firefox-problems) and only after reinstalling Firefox, the problem was gone.

So I think there is not a problem with the plugin.
